name: instai
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^10.2.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^9.0.5
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  pretty_dio_logger: ^1.4.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.2
  skeletonizer: ^2.1.0+1
  image_picker: ^1.2.1
  shared_preferences: ^2.5.3
  share_plus: ^12.0.1
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.2.6
  flutter_lints: ^5.0.0
  build_runner: ^2.10.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/billabong_regular.otf
          style: normal
        - asset: assets/fonts/billabong.ttf

